blank_issues_enabled: false
contact_links:
  - name: Structeezy Community Support
    url: https://www.facebook.com/groups/oxyprops
    about: Please ask and answer questions in the group.
  - name: Structeezy Chat
    url: https://structeezy.com/
    about: Please use the chat on the website.
